### PR TITLE
test: add test comments to header file

### PR DESCRIPTION
**Pull request by hakehuang**
for iperf we may need customerize the ports in test farm.

so add an test Anchor commnets here for each replacement

Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>

### CODE REVIEW

**Comment by TiejunMS** [comment]
Hi @hakehuang, are you able to redefine `NX_IPERF_TCP_RX_PORT` and `NX_IPERF_UDP_RX_PORT` in project settings for testing purpose?

**Comment by hakehuang** [comment]
> Hi @hakehuang, are you able to redefine `NX_IPERF_TCP_RX_PORT` and `NX_IPERF_UDP_RX_PORT` in project settings for testing purpose?

yes, we can. But modify project is not good for portable, as we plan to port this application to different IDE, set the marco in line maybe more portable friendly.

**Comment by TiejunMS** [comment]
> > Hi @hakehuang, are you able to redefine `NX_IPERF_TCP_RX_PORT` and `NX_IPERF_UDP_RX_PORT` in project settings for testing purpose?
> 
> yes, we can. But modify project is not good for porting, as we plan to port this application to different IDE, set the marco in line maybe more portable friendly.

How about adding those definitions in nx_user.h as per https://docs.microsoft.com/en-us/azure/rtos/netx-duo/chapter2#configuration-options?

**Comment by hakehuang** [comment]
> How about adding those definitions in nx_user.h as per https://docs.microsoft.com/en-us/azure/rtos/netx-duo/chapter2#configuration-options?

@TiejunMS, as these configuration is not netx stack related, it is pure the iperf related, so I would prefer to keep the code as is.

**Comment by hakehuang** [comment]
@TiejunMS any more comments on this PR. Thanks in advance.

**Pull request closed without merging**
